### ISSUE TITLE
PHP warnings regarding strict standards

### ISSUE THREAD

**Issue by msiemens** [l3rady/wp-updates-notifier#17]
When activating this plugin, I get three warnings on any admin page:

---

**Strict Standards**: Non-static method sc\_WPUpdatesNotifier::settingsUpToDate() should not be called statically in **/\<path-to-wp>/wp-content/plugins/wp-updates-notifier/wp-updates-notifier.php** on line **42**<br>
 **Strict Standards**: call\_user\_func\_array() expects parameter 1 to be a valid callback, non-static method sc\_WPUpdatesNotifier::admin\_settings\_init() should not be called statically in **/\<path-to-wp>/wp-includes/plugin.php** on line **496**<br>
 **Strict Standards**: call\_user\_func\_array() expects parameter 1 to be a valid callback, non-static method sc\_WPUpdatesNotifier::remove\_update\_nag\_for\_nonadmins() should not be called statically in **/\<path-to-wp>/wp-includes/plugin.php** on line **496**

**Comment by l3rady** [comment]
Latest issue on Github fixes this issue

**Comment by msiemens** [comment]
Awesome, thanks!
